### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by duolaiamen** [SionAn/MICCAI2024-ResTL#1]
May I ask if your BCI 2a dataset is downloaded from the official website and has not been modified? I'm having some problems trying to get your code to run on my computer, and I'm looking forward to your answer

**Comment by SionAn** [comment]
I apologize for the late response.
We have used a Python library named mne (https://mne.tools/stable/index.html) to access the datasets. 
I also multiplied 1e+6 to scale the intensity from uV to V if necessary.

**Comment by duolaiamen** [comment]
这是来自黄家超（Nelson）邮箱的假期自动回复邮件。Hello，我已经收到你的邮箱喽！
